[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TreeTraverser"
description = "Tools to work with compressed Datacubes and Trees"
dynamic = ["version"]
dependencies = [
    "fastapi",
    "pe"
]

