title: Qubed Catalogue Browser (Test)
branch: Main

stacServer:
  enabled: true
  replicas: 1
  image:
    repository: "eccr.ecmwf.int/qubed/stac_server_main"
    tag: "latest"
    pullPolicy: Always
  servicePort: 80

ingress:
  enabled: True
  tlsSecretName: "lumi-wildcard-tls"
  hostnames:
    - "qubed-test.lumi.apps.dte.destination-earth.eu"
    - "catalogue-test.lumi.apps.dte.destination-earth.eu"
