title: Qubed Catalogue Browser (Dev)
branch: Development

stacServer:
  enabled: true
  replicas: 1
  image:
    repository: "eccr.ecmwf.int/qubed/stac_server_develop"
    tag: "latest"
    pullPolicy: Always
  servicePort: 80

ingress:
  enabled: True
  tlsSecretName: "lumi-wildcard-tls"
  hostnames:
    - "qubed-dev.lumi.apps.dte.destination-earth.eu"
    - "catalogue-dev.lumi.apps.dte.destination-earth.eu"
