title: Qubed Catalogue Browser

stacServer:
  enabled: true
  replicas: 1
  image:
    repository: eccr.ecmwf.int/qubed/stac_server
    tag: 1.0.1
    pullPolicy: Always
  servicePort: 80

ingress:
  enabled: True
  tlsSecretName: "lumi-wildcard-tls"
  hostnames:
    - "qubed-dev.lumi.apps.dte.destination-earth.eu"
    - "catalogue-dev.lumi.apps.dte.destination-earth.eu"
