stacServer:
  enabled: true
  replicas: 1
  image:
    repository: "eccr.ecmwf.int/qubed/stac_server_dev"
    tag: "latest"
    pullPolicy: Always
  servicePort: 80

ingress:
  enabled: True
  tlsSecretName: "lumi-wildcard-tls"
  hostname: "qubed-dev.lumi.apps.dte.destination-earth.eu"
