title: Qubed Catalogue Browser

stacServer:
  enabled: true
  replicas: 1
  image:
    repository: eccr.ecmwf.int/qubed/stac_server
    tag: 1.0.1
    pullPolicy: Always
  servicePort: 80
  config: # config mounted as configmap
    data_files: # list of data files to load on startup, relative to mountPath
      # - on-demand-extremes-dt.json
      - extremes-dt.json
      - climate-dt.json

ingress:
  enabled: True
  tlsSecretName: "lumi-wildcard-tls"
  hostnames:
    - "qubed-dev.lumi.apps.dte.destination-earth.eu"
    - "catalogue-dev.lumi.apps.dte.destination-earth.eu"

# Shared storage PVC mounted by CronJobs and stac-server
sharedStorage:
  enabled: true
  name: qubed-shared
  accessModes:
    - ReadWriteMany
  size: 20Gi
  storageClassName: "" # set to your storage class or leave empty to use default
  mountPath: /data/shared # available as $MOUNT_PATH in scan jobs and QUBED_DATA_PREFIX in stac-server

# Configurable scan CronJobs
scanJobs:
  enabled: true
  # optional defaults applied to all jobs unless overridden
  image: eccr.ecmwf.int/qubed/fdb_scanner
  imagePullPolicy: IfNotPresent
  jobs:
    # On Demand Extremes DT Full scan every day at 4am
    - name: on-demand-extremes-dt-full-daily
      schedule: "0 4 * * *"
      command: ["python"]
      args:
        - "./scan.py --quiet --full --selector class=d1,dataset=on-demand-extremes-dt --filepath on-demand-extremes-dt.json"
      env: []

    # On Demand Extremes DT Partial scan every three hours
    - name: on-demand-extremes-dt-partial-3h
      schedule: "37 */3 * * *"
      command: ["python"]
      args:
        - "./scan.py --quiet --last_n_days=14 --selector class=d1,dataset=on-demand-extremes-dt --filepath on-demand-extremes-dt.json"
      env: []

    # Extremes-dt Daily Partial scan every three hours
    - name: extremes-dt-partial-3h
      schedule: "12 */3 * * *"
      command: ["python"]
      args:
        - "./scan.py --quiet --last_n_days=14 --selector class=d1,dataset=extremes-dt --filepath extremes-dt.json"
      env: []

    # Climate dt gen 2 Weekly on Sunday at 2am
    - name: climate-dt-gen2-weekly
      schedule: "0 2 * * 0"
      command: ["python"]
      args:
        - "./scan.py --quiet --full --selector class=d1,dataset=climate-dt,generation=2 --filepath climate-dt-gen-2.json"
      env: []
