climate_dt_keys = [
    "class",
    "dataset",
    "activity",
    "experiment",
    "generation",
    "model",
    "realization",
    "expver",
    "stream",
    "date",
    "resolution",
    "type",
    "levtype",
    "time",
    "levelist",
    "param",
]

extremes_dt_keys = [
    "class",
    "dataset",
    "expver",
    "stream",
    "date",
    "time",
    "type",
    "levtype",
    "step",
    "levelist",
    "param",
    "frequency",
    "direction",
]

on_demands_dt_keys = [
    "class",
    "dataset",
    "expver",
    "stream",
    "date",
    "time",
    "type",
    "georef",
    "levtype",
    "step",
    "number",
    "levelist",
    "param",
    "frequency",
    "direction",
    "ident",
    "instrument",
    "channel",
]

default_keys = [
    "class",
    "dataset",
    "stream",
    "activity",
    "resolution",
    "expver",
    "experiment",
    "generation",
    "model",
    "realization",
    "type",
    "date",
    "time",
    "datetime",
    "levtype",
    "levelist",
    "step",
    "param",
]


dataset_key_orders = {
    "climate-dt": climate_dt_keys,
    "extremes-dt": extremes_dt_keys,
    "on-demand-extremes-dt": on_demands_dt_keys,
    "default": default_keys,
}
