services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  web:
    image: nginx
    ports:
    - "8123:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
    - ./webapp:/usr/share/nginx/html
      