[package]
name = "qubed_meteo"
version.workspace = true
edition = "2024"
description = "Meteorological adapters to the Qubed library."
license = "Apache-2.0"
repository = "https://github.com/ecmwf/qubed"
homepage = "https://github.com/ecmwf/qubed"
documentation = "https://ecmwf.github.io/qubed/"

[dependencies]
qubed = { workspace = true }
serde = "1.0.228"
serde_json = "1.0.145"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false, optional = true }
fdb = { git = "ssh://git@github.com/ecmwf/fdb.git", branch = "develop", optional = true }
metkit = { git = "ssh://git@github.com/ecmwf/metkit.git", branch = "develop", optional = true }
eckit = { git = "ssh://git@github.com/ecmwf/eckit.git", branch = "develop", optional = true }

[dev-dependencies]
tempfile = "3"

[features]
default = []
fdb-support = ["dep:fdb", "dep:metkit", "dep:eckit"]
opendata-support = ["reqwest"]

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[[example]]
name = "read_from_fdb_list"
required-features = ["fdb-support"]

